name: URL Ping and Keep Alive

on:
  schedule:
    - cron: '*/5 * * * *'    # Run every 5 minutes (for testing)
  push:
    branches: [ main ]      # Runs on push to main
  workflow_dispatch:        # Allows manual triggers

jobs:
  ping:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Send ping request with timestamp
      run: |
        echo "Ping executed at $(date)"
        curl -X GET https://visitl.onrender.com/
        
    - name: Update timestamp
      run: |
        date > timestamp.txt
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add timestamp.txt
        git commit -m "Update timestamp [skip ci]"  # Add [skip ci] to avoid recursive triggers
        git push

    - name: Log schedule time
      run: echo "Job completed at $(date)"