name: URL Ping

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggers

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send ping request
      run: |
        curl -X GET https://visitl.onrender.com/